arch: arm64-graviton2
virt: lxd
os: linux
dist: focal

language: node_js
node_js:
  - 16
  - 14
  - 12
services:
  - docker

before_install:
  - docker-compose build
script:
  - docker-compose run test