version: "3.7"
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 10
  test:
    build: .
    depends_on:
      - db
    links:
      - db:db
    # Unfortunately there is no reliable way to wait for postgres
    # More info: https://github.com/docker-library/postgres/issues/146
    command: sh -c "yarn test"
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      PGHOST: 'db'
      PGUSER: 'postgres'
      PGDATABASE: 'postgres'
    volumes:
      - .:/test